version: '3.8'

services:
  app:
    build: .
    ports:
      - "30500:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "https://admin.clxnightrun.com/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s